name = "yjs-sveltekit-demo"
main = "build/_worker.js"
compatibility_date = "2024-06-01"
workers_dev = true

[vars]
PUBLIC_YJS_ENDPOINT = "wss://yjs-room-server.YOUR_SUBDOMAIN.workers.dev/room/visitors"
